# version: '3.8'

services:
  web:
    container_name: auction_web
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://auction:auction@db:5432/auction
    depends_on:
      - db
  db:
    container_name: auction_db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=auction
      - POSTGRES_PASSWORD=auction
      - POSTGRES_DB=auction

  cache:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - 6379:6379

volumes:
  postgres_data: