"""update user

Revision ID: 1ec69be6af5a
Revises: 67a1450cde07
Create Date: 2025-01-12 17:13:39.796737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ec69be6af5a'
down_revision: Union[str, None] = '67a1450cde07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bids', 'bet_price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bids', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bids', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_bids_id', table_name='bids')
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'discription',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'start_price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'current_price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('products', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('products', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'COMPLETED', name='productstatus'),
               nullable=False)
    op.alter_column('products', 'current_winner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_products_id', table_name='products')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'birthday',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_password_hash', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_column('users', 'sex')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_password_hash', 'users', ['password_hash'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'birthday',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_products_id', 'products', ['id'], unique=False)
    op.alter_column('products', 'current_winner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'COMPLETED', name='productstatus'),
               nullable=True)
    op.alter_column('products', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('products', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('products', 'current_price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'start_price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'discription',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_bids_id', 'bids', ['id'], unique=False)
    op.alter_column('bids', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bids', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bids', 'bet_price',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
