"""update products

Revision ID: 332c8f2314e6
Revises: 1ec69be6af5a
Create Date: 2025-01-12 18:12:46.751485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '332c8f2314e6'
down_revision: Union[str, None] = '1ec69be6af5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'current_winner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'current_winner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
