"""update columns

Revision ID: 8fe25f1e8e3d
Revises: edefc164091d
Create Date: 2024-12-23 20:57:44.277720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe25f1e8e3d'
down_revision: Union[str, None] = 'edefc164091d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('start_price', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('current_price', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('products', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.drop_column('products', 'end_date')
    op.drop_column('products', 'start_date')
    op.drop_column('products', 'current_price')
    op.drop_column('products', 'start_price')
    # ### end Alembic commands ###
